### PR TITLE
Fix a logical issue.

### PR DESCRIPTION
**Pull request by ghost**
Please read a commend in code.

### CODE REVIEW

**Comment by Mds92** [comment]
Assume user wants to parse the following string:
"چهارشنبه 5 آذر 93"
I wrote these line to enable this feature, otherwise how we can find year from above string?
Above string format is very popular, so web can use a logic to parse it, isn't it?

**Comment by ghost** [comment]
i really don't understand why number 93 should be related to the year 1393 and not 1493 or 1593 or 2093!
In my app for birth date 58 i receive 1458! that it's certainly not correct .
Obviously, if the input is incomplete, output would be incomplete. You are not responsible for the careless user or incomplete data. in your opinion why Banking applications used four digits for the year? Okay that's why! :). Adding 13 or 14 should be done with the user's own responsibility.

**Comment by Mds92** [comment]
Well, in Iran people used to write year in short form, like 93 that means 1393, or 94 means 1394.
No one relates 93 to 1493.

**Comment by ghost** [comment]
it's your project and I'm not gonna force you to accept or merge the commit, Ultimately, the decision is yours. but In my opinion, it's not good idea that machine think like people. for people, relative accuracy will be enough but the machine requires absolute precision.Year 2000 problem is the result of one of these careless.
Suppose our program receive a time span of several hundred years of historical data as an input, for result all date must be arranged in chronological order. in this case your lib will not benefit . You've written a multipurpose library and defensive programming is one of important requirements for it.
good luck.

**Comment by Mds92** [comment]
First, It's a OpenSource project, so you can edit your own version.
Please write a date string sample, I've tested the following, it doesn't have any problems.
"چهارشنبه 5 آذر 2000"

**Comment by ghost** [comment]
Yes i edited it at first.
"چهارشنبه 5 آذر 2000" returned 2000
"چهارشنبه 5 آذر 1394" returned 1394
"چهارشنبه 5 آذر 94" returned 1394 (in edited version returned 0094)
"چهارشنبه 5 آذر 58" returned 1458 (in edited version returned 0058)

**Comment by Mds92** [comment]
I created this feature base on some requests, so I can't remove it,
But I changed to supports all your formats:
"چهارشنبه 5 آذر 2000" returned 2000
"چهارشنبه 5 آذر 1394" returned 1394
"چهارشنبه 5 آذر 94" returned 1394
"چهارشنبه 5 آذر 58" returned 1358

**Comment by ghost** [comment]
Yes, now it's more tolerable,  library can be used at least until the year 1400 
You'd better hope your library does not use in sensitive applications. :)
We speak English here. Code comments in Persian!
what is the story?

**Comment by Mds92** [comment]
Well, I should comment in Persian for Persian developers and shows the correct output formats of methods.

**Pull request closed without merging**
